<?php

use Illuminate\Database\Seeder;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ingredients')->insert([
            ['name' => 'Rhum blanc',
            'alcohol_degree' => '40',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Citron vert frais',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '4'],
            ['name' => 'Menthe fraîche',
            'alcohol_degree' => '0',
            'categorie_id' => '5',
            'unit_id' => '5'],
            ['name' => 'Sirop de canne',
            'alcohol_degree' => '0',
            'categorie_id' => '3',
            'unit_id' => '5'],
            ['name' => 'Eau gazeuse',
            'alcohol_degree' => '0',
            'categorie_id' => '2',
            'unit_id' => '1'],
            ['name' => 'Jus ananas',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '1'],
            ['name' => 'Lait de coco',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '1'],
            ['name' => 'Cachaça',
            'alcohol_degree' => '40',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Tequila',
            'alcohol_degree' => '38',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Triple sec',
            'alcohol_degree' => '35',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Jus de citron vert pressé',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '1'],
            ['name' => 'Vodka',
            'alcohol_degree' => '40',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Liqueur de melon',
            'alcohol_degree' => '20',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Crème de mûre',
            'alcohol_degree' => '16',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Nectar de cranberry',
            'alcohol_degree' => '16',
            'categorie_id' => '3',
            'unit_id' => '1'],
            ['name' => 'Rhum ambré',
            'alcohol_degree' => '45',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Nectar de maracujà',
            'alcohol_degree' => '0',
            'categorie_id' => '3',
            'unit_id' => '1'],
            ['name' => 'Sirop de grenadine',
            'alcohol_degree' => '0',
            'categorie_id' => '3',
            'unit_id' => '1'],
            ['name' => 'Lait',
            'alcohol_degree' => '0',
            'categorie_id' => '6',
            'unit_id' => '1'],
            ['name' => 'Jus de citron pressé',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '1'],
            ['name' => 'Sel',
            'alcohol_degree' => '0',
            'categorie_id' => '6',
            'unit_id' => '6'],
            ['name' => 'Scotch whisky',
            'alcohol_degree' => '40',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Jus orange',
            'alcohol_degree' => '0',
            'categorie_id' => '4',
            'unit_id' => '1'],
            ['name' => 'Liqueur de cerise',
            'alcohol_degree' => '20',
            'categorie_id' => '1',
            'unit_id' => '1'],
            ['name' => 'Vermouth rouge',
            'alcohol_degree' => '15',
            'categorie_id' => '1',
            'unit_id' => '1'],
        ]);
    }
}
